EComp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name


urlpatterns = [
		path('create/', BlogCreateView.as_view(), name='create'),  # создание
		path('', BlogListView.as_view(), name='list'),
		path('view/<slug:slug>', BlogDetailView.as_view(), name='view'),
		path('edit/<slug:slug>', BlogUpdateView.as_view(), name='edit'),
		path('delete/<slug:slug>', BlogDeleteView.as_view(), name='delete'),
		path('activity/<slug:slug>', toggle_activity, name='toggle_activity'),
]

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
	title = models.CharField(max_length=50, verbose_name='Заголовок')
	slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
	body = models.TextField(verbose_name='Содержимое')
	image = models.ImageField(upload_to='images_blog/', verbose_name='Изображение', **NULLABLE)
	updated_at = models.DateField(auto_now=True, verbose_name='Последнее изменение')
	is_published = models.BooleanField(verbose_name='Опубликовано', default=True)
	views_count = models.IntegerField(verbose_name='просмотры', default=0)


	def __str__(self):
		return f'{self.title} - {self.slug}'

	class Meta:
		verbose_name = 'блог'
		verbose_name_plural = 'блоги'

blog/forms.py
from django import forms
from blog.models import Blog


class StyleFormMixin:
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field_name, field in self.fields.items():
			if field_name != 'is_published':
				field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, forms.ModelForm):
	class Meta:
		model = Blog
		fields = ('title', 'body', 'image', 'is_published')

blog/views.py
import slugify as slugify
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from EComp import settings
from blog.forms import BlogForm
from blog.models import Blog
from django.core.mail import send_mail


class BlogCreateView(CreateView):
	model = Blog
	# permission_required = 'blog.add_blog'
	form_class = BlogForm
	success_url = reverse_lazy('blog:list')
	extra_context = {
			'title': "Добавить публикацию",
	}

	def form_valid(self, form):
		if form.is_valid():
			new_mat = form.save()
			new_mat.slug = slugify(new_mat.title)
			new_mat.save()

		return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
	model = Blog
	permission_required = 'blog.change_blog'
	form_class = BlogForm
	success_url = reverse_lazy('blog:list')
	extra_context = {
			'title': "Редактировать публикацию",
	}

	def form_valid(self, form):
		if form.is_valid():
			new_mat = form.save()
			new_mat.slug = slugify(new_mat.title)
			new_mat.save()

		return super().form_valid(form)

	def get_success_url(self):
		return reverse('blog:view', args=[self.kwargs.get('slug')])


class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Blog
	success_url = reverse_lazy('blog:list')
	extra_context = {
			'title': "Удаление публикации",
	}

	def test_func(self):
		return self.request.user.is_superuser


class BlogListView(ListView):
	model = Blog
	extra_context = {
			'title': "Все публикации",
	}

	def get_queryset(self, *args, **kwargs):
		queryset = super().get_queryset(*args, **kwargs)
		queryset = queryset.filter(is_published=True)
		return queryset


class BlogDetailView(DetailView):
	model = Blog
	extra_context = {
			'title': "Приятного прочтения",
	}

	def get_object(self, queryset=None):
		self.object = super().get_object(queryset)
		self.object.views_count += 1
		self.object.save()
		if self.object.views_count == 100:
			send_mail(
					subject='Отлично!',
					message='Вашу статью посмотрели уже 100 человек!',
					from_email=settings.EMAIL_HOST_USER,
					recipient_list=['astrulkov53@gmail.com'],
					fail_silently=False
			)
		return self.object


def toggle_activity(request, slug):
	blog_item = get_object_or_404(Blog, slug=slug)
	if blog_item.is_published:
		blog_item.is_published = False
	else:
		blog_item.is_published = True

	blog_item.save()

	return redirect(reverse('blog:list'))

blog/templates/blog/blog_confirm_delete.html
{% extends "catalog/base.html" %}
{% block content %}
    {% include 'catalog/includes/inc_catalog.html' %}
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить материал "{{ object.title }}"?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
    {% include 'catalog/includes/inc_catalog.html' %}
    {% load my_tags %}
    <div class="container">
        <div class="row">
            <div class="col-5">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-text">Статья: "{{ object.title }}"({{ object.slug }})</h5>
                        <p class="card-text">{{ object.body }}</p>
                    </div>
                    <div class="card-footer">Просмотры: {{ object.views_count }}</div>
                {% if perms.blog.change_blog %}
                    {% if object.is_published %}
                        <a class="btn btn-warning" href=
                                "{% url 'blog:toggle_activity' object.slug %}">Деактивировать</a>
                    {% else %}
                        <a class="btn btn-success" href=
                                "{% url 'blog:toggle_activity' object.slug %}">Активировать</a>
                    {% endif %}
                {% endif %}
                </div>
            </div>
            <div class="col-7">
                    <div class="card-body">
                        <p><img src="{% mediapath object.image %}" width="400"></p>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "catalog/base.html" %}
{% block content %}
    {% include 'catalog/includes/inc_catalog.html' %}
    {#    <div class="container">#}
    {#        <div class="col-12">#}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    {% include 'catalog/includes/inc_catalog.html' %}
    <div class="container">
    {% if perms.blog.add_blog %}
        <div class="col-12 mb-5">
            <a class="btn btn-outline-primary" href="{% url "blog:create" %}">Добавить материал</a>
        </div>
    {% endif %}
        {% for object in object_list %}
            <div class="row text-center">
                <div class="row my-2">
                    <div class="col-3">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <p class="card_text">{{ object|title }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'blog:view' object.slug %}"
                                           class="mx-2 btn btn-sw btn-outline-primary">View</a>
                                    {% if perms.blog.change_blog %}
                                        <a href="{% url 'blog:edit' object.slug %}" type="button"
                                           class="mx-2 btn btn-sw btn-outline-warning">Edit</a>
                                     {% endif %}
                                        {% if user.is_superuser %}
                                        <a href="{% url 'blog:delete' object.slug %}" type="button"
                                           class="mx-2 btn btn-sw btn-outline-danger">Delete</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}