EComp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name


urlpatterns = [
		path('create/', BlogCreateView.as_view(), name='create'),  # создание
		path('', BlogListView.as_view(), name='list'),
		path('view/<slug:slug>', BlogDetailView.as_view(), name='view'),
		path('edit/<slug:slug>', BlogUpdateView.as_view(), name='edit'),
		path('delete/<slug:slug>', BlogDeleteView.as_view(), name='delete'),
		path('activity/<slug:slug>', toggle_activity, name='toggle_activity'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, RegisterDoneView, user_activate, UserUpdateView, \
	generate_new_password

app_name = UsersConfig.name

urlpatterns = [
		path('', LoginView.as_view(), name='login'),
		path('logout/', LogoutView.as_view(), name='logout'),
		path('accounts/register/', RegisterView.as_view(), name='register'),
		path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
		path('accounts/activate/<str:sign>', user_activate, name='activate'),
		path('profile/', UserUpdateView.as_view(), name='profile'),
		path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from catalog.models import NULLABLE


class User(AbstractUser):
	username = None

	email = models.EmailField(unique=True, verbose_name='Email')

	avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
	phone = models.CharField(max_length=15, verbose_name='Номер телефона', **NULLABLE)
	country = models.CharField(max_length=35, verbose_name='Страна', **NULLABLE)
	# email_verify = models.BooleanField(default=False, verbose_name='')
	is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошел активацию?' )

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
# from catalog.forms import StyleFormMixin
from users.models import User
from users.signals import post_register


class StyleFormMixin:
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field_name, field in self.fields.items():
			if field_name != 'is_staff':
				field.widget.attrs['class'] = 'form-control'


class UserProfileForm(StyleFormMixin, UserChangeForm):
	"""Добавление формы профиля пользователя"""
	class Meta:
		model = User
		fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'avatar', 'country', 'is_staff')

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		self.fields['password'].widget = forms.HiddenInput()


class RegisterForm(StyleFormMixin, UserCreationForm):
	"""Добавление формы регистрации пользователя с верификацией"""

	def save(self, commit=True):
		user = super().save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		user.is_active = False
		user.is_activated = False
		if commit:
			user.save()
		post_register.send(RegisterForm, instance=user)
		return user

	class Meta:
		model = User
		fields = ('first_name', 'email', 'password1', 'password2', 'avatar', 'phone', 'country', 'is_staff')

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.views.generic import CreateView, UpdateView
from django.views.generic.base import TemplateView

from users.models import User
from django.urls import reverse_lazy, reverse

from users.forms import RegisterForm, UserProfileForm

from django.core.signing import BadSignature

from .services import send_new_password
from .utilities import signer
from django.core.mail import send_mail
from django.conf import settings


class LoginView(BaseLoginView):
	template_name = 'users/login.html'



class LogoutView(BaseLogoutView):
	pass


class RegisterView(CreateView):
	model = User
	# form_class = UserForm
	form_class = RegisterForm
	success_url = reverse_lazy('users:register_done')
	template_name = 'users/register.html'
	success_message = 'Вы успешно зарегистрировались'


class RegisterDoneView(TemplateView):
	template_name = 'users/register_done.html'


def user_activate(request, sign):
	try:
		email = signer.unsign(sign)
	except BadSignature:
		return render(request, 'users/activation_failed.html')

	user = get_object_or_404(User, email=email)

	if user.is_activated:
		template = 'users/activation_done_earlier.html'
	else:
		template = 'users/activation_done.html'
		user.is_active = True
		user.is_activated = True
		user.save()

	return render(request, template)


class UserUpdateView(LoginRequiredMixin, UpdateView):
	models = User
	success_url = reverse_lazy('users:profile')
	form_class = UserProfileForm

	def get_object(self, queryset=None): # Избавляемся от входящего параметра pk
		return self.request.user


@login_required
def generate_new_password(request):
	new_password = User.objects.make_random_password()
	request.user.set_password(new_password)
	request.user.save()
	send_new_password(request.user.email, new_password)
	return redirect(reverse('catalog:home'))

users/templates/users/activation_done.html
{% extends 'catalog/base.html' %}
{% block title %}Активация выполнена{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Активация</div>
                <div class="card-body">
                    <p>Пользователь с таким именем успешно активирован</p>
                    <p><a href=" {%  url 'users:login' %}">Войти на сайт</a></p>
                </div>
                <div class="card-footer">Поздравляем!</div>
            </div>
        </div>
    </div>

    {#<h2>Регистрация</h2>#}
    {#    <p>Регистрация пользователя завершена.</p>#}
    {#    <p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>#}
{% endblock %}

users/templates/users/activation_done_earlier.html
{% extends 'catalog/base.html' %}
{% block title %}Ошибка при активации{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Активация</div>
                <div class="card-body">
                    <p>Пользователь с таким именем был активирован ранее</p>
                    <p><a href=" {%  url 'users:login' %}">Войти на сайт</a></p>
                </div>
                <div class="card-footer">Отличного дня!</div>
            </div>
        </div>
    </div>

    {#<h2>Регистрация</h2>#}
    {#    <p>Регистрация пользователя завершена.</p>#}
    {#    <p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>#}
{% endblock %}

users/templates/users/activation_failed.html
{% extends 'catalog/base.html' %}
{% block title %}Ошибка при активации{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Активация</div>
                <div class="card-body">
                    <p>Активация пользователя с таким именем прошла неудачно.</p>
                    <p><a href=" {%  url 'users:register' %}">Зарегистрироваться повторно</a></p>
                </div>
                <div class="card-footer">Упс!</div>
            </div>
        </div>
    </div>

    {#<h2>Регистрация</h2>#}
    {#    <p>Регистрация пользователя завершена.</p>#}
    {#    <p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>#}
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="p-2 btn btn-outline-primary">Вход</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="p-2 btn btn-outline-primary">Регистрация</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register_done.html
{% extends 'catalog/base.html' %}
{% block title %}Регистрация завершена{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Регистрация</div>
                <div class="card-body">
                    <p>Регистрация пользователя завершена.</p>
                    <p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>
                </div>
                <div class="card-footer">Поздравляем!</div>
            </div>
        </div>
    </div>

    {#<h2>Регистрация</h2>#}
    {#    <p>Регистрация пользователя завершена.</p>#}
    {#    <p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>#}
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Мой профиль
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="p-2 btn btn-outline-primary">Сохранить</button>
                    </form>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:generate_new_password' %}">Сгенерировать пароль</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}