EComp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name


urlpatterns = [
		path('create/', BlogCreateView.as_view(), name='create'),  # создание
		path('', BlogListView.as_view(), name='list'),
		path('view/<slug:slug>', BlogDetailView.as_view(), name='view'),
		path('edit/<slug:slug>', BlogUpdateView.as_view(), name='edit'),
		path('delete/<slug:slug>', BlogDeleteView.as_view(), name='delete'),
		path('activity/<slug:slug>', toggle_activity, name='toggle_activity'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from .apps import CatalogConfig
from .views import ProductListView, CategoryListView, ProductDetailView, CatalogListView, ContactsCreateView, \
	ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = CatalogConfig.name


urlpatterns = [
		path('', ProductListView.as_view(), name='home'),
		path('contacts/', ContactsCreateView.as_view(), name='contacts'),
		path('one_product/<int:pk>', cache_page(60*5)(ProductDetailView.as_view()), name='one_product'),
		path('all_products/<int:pk>', CatalogListView.as_view(), name='all_products'),
		path('category/', cache_page(60*5)(CategoryListView.as_view()), name='category'),
		path('product/create/', ProductCreateView.as_view(), name='product_create'),
		path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
		path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, RegisterDoneView, user_activate, UserUpdateView, \
	generate_new_password

app_name = UsersConfig.name

urlpatterns = [
		path('', LoginView.as_view(), name='login'),
		path('logout/', LogoutView.as_view(), name='logout'),
		path('accounts/register/', RegisterView.as_view(), name='register'),
		path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
		path('accounts/activate/<str:sign>', user_activate, name='activate'),
		path('profile/', UserUpdateView.as_view(), name='profile'),
		path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

catalog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db import connection

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
	name_category = models.CharField(max_length=100, verbose_name='Категория')
	description_category = models.TextField(verbose_name='Описание', **NULLABLE)
	image = models.ImageField(upload_to='category/', verbose_name='Изображение', **NULLABLE)

	def __str__(self):
		return f'{self.name_category}'

	class Meta:
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'

	@classmethod
	def truncate_table_restart_id(cls):
		with connection.cursor() as cursor:
			cursor.execute(f'ALTER SEQUENCE catalog_category_id_seq RESTART WITH 1;')


class Product(models.Model):
	name_product = models.CharField(max_length=100, verbose_name='Наименование')
	description_product = models.TextField(verbose_name='Описание', **NULLABLE)
	name_category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
	price = models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')
	image = models.ImageField(upload_to='product/', verbose_name='Изображение', **NULLABLE)
	created_at = models.DateField(verbose_name='Дата создания')
	updated_at = models.DateField(auto_now=True, verbose_name='Последнее изменение')
	views_count = models.IntegerField(verbose_name='Просмотры', default=0)
	slug = models.SlugField(verbose_name='slug', max_length=150, null=True, blank=True)
	creator = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, **NULLABLE)
	is_published = models.BooleanField(default=False, verbose_name='опубликовано')


	def __str__(self):
		return f'{self.name_product}'

	class Meta:
		verbose_name = 'Товар'
		verbose_name_plural = 'Товары'

	@classmethod
	def truncate_table_restart_id(cls):
		with connection.cursor() as cursor:
			cursor.execute(f'ALTER SEQUENCE catalog_product_id_seq RESTART WITH 1;')


class Contacts(models.Model):
	contact_name = models.CharField(max_length=30, verbose_name='Ваше имя')
	contact_email = models.CharField(max_length=30, verbose_name='Ваш email')
	contact_text = models.TextField(verbose_name='Ваше сообщение', default='Cпасибо')

	def __str__(self):
		return f'{self.contact_name} - {self.contact_email}'

	class Meta:
		verbose_name = 'контакт'
		verbose_name_plural = 'контакты'
		ordering = ('contact_name',)


class Versions(models.Model):
	product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='продукт')
	number_version = models.ForeignKey('NumberVersion', on_delete=models.CASCADE, verbose_name='номер версии')
	name = models.ForeignKey('StatusProduct', on_delete=models.CASCADE, verbose_name='наименование')
	active_version = models.BooleanField(verbose_name='признак версии')

	def __str__(self):
		return f'{self.name}, {self.number_version}'

	class Meta:
		verbose_name = 'версия'
		verbose_name_plural = 'версии'

	@classmethod
	def truncate_table_restart_id(cls):
		with connection.cursor() as cursor:
			cursor.execute(f'ALTER SEQUENCE catalog_versions_id_seq RESTART WITH 1;')


class StatusProduct(models.Model):
	status_name = models.CharField(max_length=150, verbose_name='статус товара на складе', unique=True)

	@classmethod
	def truncate_table_restart_id(cls):
		with connection.cursor() as cursor:
			cursor.execute(f'ALTER SEQUENCE catalog_statusproduct_id_seq RESTART WITH 1;')


	def __str__(self):
		return f'{self.status_name}'

	class Meta:
		verbose_name = 'статус'
		verbose_name_plural = 'статусы'


class NumberVersion(models.Model):
	status_name = models.IntegerField(verbose_name='номер версии', unique=True)

	@classmethod
	def truncate_table_restart_id(cls):
		with connection.cursor() as cursor:
			cursor.execute(f'ALTER SEQUENCE catalog_numberversion_id_seq RESTART WITH 1;')

	def __str__(self):
		return f'{self.status_name}'

	class Meta:
		verbose_name = 'номер версии'
		verbose_name_plural = 'номера версии'

catalog/forms.py
from django import forms
from django.forms import BaseInlineFormSet

from catalog.models import Product, Versions, Contacts, StatusProduct


class StyleFormMixin:
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field_name, field in self.fields.items():
			field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

	class Meta:
		model = Product
		fields = ('name_product', 'description_product', 'name_category', 'image', 'price', 'created_at',)

	def clean_name_product(self):
		cleaned_data = self.cleaned_data['name_product']
		forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман',
							'полиция', 'радар']

		for obj in forbidden_words:
			if obj in cleaned_data:
				raise forms.ValidationError("Продукт запрещен в нашем магазине")

		return cleaned_data

	def clean_description_product(self):
		cleaned_data = self.cleaned_data['description_product']
		forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман',
							'полиция', 'радар']

		for obj in forbidden_words:
			if obj in cleaned_data:
				raise forms.ValidationError("В описании присутствуют запрещенные слова")

		return cleaned_data


class VersionForm(forms.ModelForm):
	class Meta:
		model = Versions
		# exclude = ('product',)
		fields = ('number_version', 'name', 'active_version')
		widgets = {
				'number_version': forms.Select(attrs={'class': 'form-control'}),
				'name': forms.Select(attrs={'class': 'form-control'}),
				'active_version': forms.NullBooleanSelect(attrs={'class': 'form-control'}),

		}


class ContactForm(StyleFormMixin, forms.ModelForm):
	class Meta:
		model = Contacts
		fields = ('contact_name', 'contact_email', 'contact_text',)


class VersionBaseInlineFormSet(BaseInlineFormSet):
	def clean(self):
		super().clean()
		active_list = [form.cleaned_data['active_version'] for form in self.forms if 'active_version' in
						form.cleaned_data]
		if active_list.count(True) > 1:
			print("У продукта возможна только одна активная версия!")
			raise forms.ValidationError("У продукта возможна только одна активная версия!")


class ProductModeratorForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field_name, field in self.fields.items():
			if field_name != 'is_published':
				field.widget.attrs['class'] = 'form-control'

	class Meta:
		model = Product
		fields = ('is_published', 'description_product', 'name_category',)

catalog/views.py
import json

from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, \
	PermissionRequiredMixin
from django import forms
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from catalog.models import Product, Category, Contacts, Versions
from catalog.forms import ProductForm, VersionForm, ContactForm, VersionBaseInlineFormSet, \
	ProductModeratorForm
from django.db import transaction

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from catalog.services import cached_category


class ProductListView(LoginRequiredMixin, ListView):
	model = Product
	extra_context = {
			'title': "Все товары"
	}
	paginate_by = 3

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		for product in context['object_list']:
			active_version = product.versions_set.filter(active_version=True).first()
			if active_version:
				product.active_version_number = active_version.number_version
				product.active_version_name = active_version.name
			else:
				product.active_version_number = None
				product.active_version_name = None
		return context


class ProductDetailView(LoginRequiredMixin, DetailView):
	model = Product

	def get_object(self, queryset=None):
		self.object = super().get_object(queryset)
		self.object.views_count += 1
		self.object.save()
		return self.object

	def get_context_data(self, *args, **kwargs):
		context_data = super().get_context_data(*args, **kwargs)

		product_item = Product.objects.get(pk=self.kwargs.get('pk'))
		context_data['title'] = f'{product_item.name_product}'

		return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
	model = Product
	form_class = ProductForm
	success_url = reverse_lazy('catalog:home')

	def get_context_data(self, **kwargs):
		context_data = super().get_context_data(**kwargs)
		context_data['category'] = Category.objects.all()
		context_data['title'] = 'Создание товара'
		VersionFormSet = inlineformset_factory(self.model, Versions, form=VersionForm, extra=1)
		if self.request.method == 'POST':
			formset = VersionFormSet(self.request.POST)
		else:
			formset = VersionFormSet()

		context_data['formset'] = formset
		context_data['name_category'] = cached_category()
		return context_data

	def form_valid(self, form):
		self.object = form.save()
		self.object.user = self.request.user
		self.object.save()
		product = form.save(commit=False)
		product.creator = self.request.user
		context_data = self.get_context_data()
		formset = context_data['formset']
		# with transaction.atomic():
		if form.is_valid():
			self.object = form.save()
			if formset.is_valid():
				formset.instance = self.object
				formset.save()
			else:
				return self.form_invalid(form)

		return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Product
	form_class = ProductForm
	permission_required = 'catalog.change_product'

	def get_success_url(self):
		return reverse('catalog:product_update', args=[self.kwargs.get('pk')])

	def get_context_data(self, **kwargs):
		context_data = super().get_context_data(**kwargs)
		context_data['category'] = Category.objects.all()
		context_data['title'] = 'Редактирование товара'
		VersionFormSet = inlineformset_factory(
				Product, Versions, form=VersionForm, extra=1,
				formset=VersionBaseInlineFormSet
		)
		if self.request.method == 'POST':
			formset = VersionFormSet(self.request.POST, instance=self.object)
		else:
			formset = VersionFormSet(instance=self.object)

		context_data['formset'] = formset
		return context_data

	def form_valid(self, form):
		context_data = self.get_context_data()
		formset = context_data['formset']
		with transaction.atomic():
			if form.is_valid():
				self.object = form.save()
				if formset.is_valid():
					formset.instance = self.object
					formset.save()
				else:
					return self.form_invalid(form)

		return super().form_valid(form)

	def get_form_class(self):
		if self.request.user.is_staff and self.request.user.groups.filter(name='moderator').exists():
			return ProductModeratorForm
		return ProductForm

	def test_func(self):
		_user = self.request.user
		_instance: Product = self.get_object()
		custom_perms: tuple = (
				'catalog_app.set_is_published',
				'catalog_app.set_name_category',
				'catalog_app.set_description_product',
		)
		if _user == _instance.creator:
			return True
		elif _user.groups.filter(name='moderator') and _user.has_perms(custom_perms):
			return True
		return self.handle_no_permission()


class ProductDeleteView(LoginRequiredMixin, DeleteView):
	model = Product
	success_url = reverse_lazy('catalog:home')
	extra_context = {
			'title': "Удаление товара",
	}


class CategoryListView(ListView):
	model = Category
	extra_context = {
			'title': "Категории товаров",
	}
	paginate_by = 3


class CatalogListView(LoginRequiredMixin, ListView):
	model = Product

	def get_queryset(self):
		queryset = super().get_queryset()
		queryset = queryset.filter(name_category_id=self.kwargs.get('pk'))
		return queryset

	def get_context_data(self, *args, **kwargs):
		context_data = super().get_context_data(*args, **kwargs)

		category_item = Category.objects.get(pk=self.kwargs.get('pk'))
		context_data['category_pk'] = category_item.pk
		context_data['title'] = f'{category_item.name_category}'

		return context_data


class ContactsCreateView(CreateView):
	model = Contacts
	form_class = ContactForm
	success_url = reverse_lazy('catalog:contacts')
	extra_context = {
			'title': "Обратная связь"
	}

	def form_valid(self, form):
		if form.is_valid():
			new_contact = form.save()
			new_contact.personal_manager = self.request.user
			new_contact.save()
			contact_dict = {
					"Имя": new_contact.contact_name,
					"Почта": new_contact.contact_email,
					"Сообщение": new_contact.contact_text,
			}
			with open("contacts.json", 'a', encoding='UTF-8') as f:
				json.dump(contact_dict, f, indent=2, ensure_ascii=False)

		return super().form_valid(form)

catalog/templates/catalog/all_products.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    {% include 'catalog/includes/inc_product.html' %}
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
            {% for object in object_list %}
                <div class="col-4" >
                    <div class="card shadow-sm" Style="border-color:#7777ff">
                        <div class="card-body">
                            <div class="container">
                                <div class="card shadow-sm">
                                    <p><img src="{% mediapath object.image %}" width="150" height="150"> </p>
                                </div>
                            </div>
                            <h6 class="card-text">Наименование:</h6>
                            <p class="card-text">{{ object.name_product| title|truncatechars:30 }} </p>
                            <h6 class="card-text">Описание:</h6>
                            <p class="card-text">{{ object.description_product|truncatechars:50 }}</p>
                            <h6 class="card-text">Стоимость:</h6>
                            <p class="card-text">{{ object.price }} руб.</p>
                            <div class="d-flex justify-content-between align-items-center"></div>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">В корзину</button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Компания ООО EComp оптовый поставщик и производитель электронных
            компонентов и электротехнической продукции">
    <meta name="author" content="Александр Струльков">
    <title>EComp</title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">EComp</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "catalog:category" %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "blog:list" %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "catalog:contacts" %}">Контакты</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url "users:profile" %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url "users:logout" %}">Выход</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary mb-2" href="{% url "users:login" %}">Вход</a>
            <a class="p-2 btn btn-outline-primary" href="{% url "users:register" %}">Регистрация</a>
        {% endif %}
    </nav>
        {% include 'catalog/includes/inc_product.html' %}
</div>
{#<!-- Блок навигации -->#}
{#{% block navigation %}#}
{#{% endblock %}#}
<!-- Блок контента -->
{% block content %}
{% endblock %}

<div class='container'>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                EComp
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url "catalog:contacts" %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/catalog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
{% include 'catalog/includes/inc_catalog.html' %}
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
            {% for object in object_list %}
                <div class="col-4" >
                    <div class="card shadow-sm" Style="border-color:#7777ff">
                        <div class="card-body">
{#                            <div class="container">#}
{#                                <div class="card shadow-sm">#}
                                    <p><img src="{% mediapath object.image %}" width="150" height="150"> </p>
{#                                </div>#}
{#                            </div>#}
                            <h6 class="card-text">Наименование:</h6>
                            <p class="card-text">{{ object.name_product| title|truncatechars:30 }} </p>
                            <h6 class="card-text">Описание:</h6>
                            <p class="card-text">{{ object.description_product|truncatechars:50 }}</p>
                            <h6 class="card-text">Стоимость:</h6>
                            <p class="card-text">{{ object.price }} руб.</p>
                            <div class="d-flex justify-content-between align-items-center"></div>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">В корзину</button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/category.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    {% include 'catalog/includes/inc_product.html' %}
    <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow" Style="border-color:#7777ff">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.name_category }}</h4>
                        </div>
                        <div class="card shadow-sm">
                            <p><img src="{% mediapath object.image %}" width="250" height="250"> </p>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title"></h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>Описание: {{ object.description_category|truncatechars:100 }}</li>
                                <li>*******************************</li>
                                <li>Категория: {{ object.name_category }}</li>
                            </ul>
                            <a href="/all_products/{{ object.pk }}" type="button" class="btn btn-lg btn-block
                            btn-outline-primary">Все товары категории</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    {% include 'catalog/includes/inc_catalog.html' %}
    <div class="container">
        <div class="col-12 text-center mb-3">
            {% if page_obj.has_other_pages %}
                {% if page_obj.has_previous %}
                    <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">Назад</a>
                {% endif %}
                {% if page_obj.has_next %}
                    &nbsp;&nbsp;|&nbsp;&nbsp;
                    <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">Далее</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow" Style="border-color:#7777ff">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.name_category }}</h4>
                        </div>
                        <p><img src="{% mediapath object.image %}" width="200" height="200"></p>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title"></h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>Описание: {{ object.description_category|truncatechars:100 }}</li>
                                <li>*******************************</li>
                                <li>Категория: {{ object.name_category }}</li>
                            </ul>
                            <a href="/all_products/{{ object.pk }}" type="button" class="btn btn-lg btn-block
                            btn-outline-primary">Все товары категории</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/contacts_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    {% include 'catalog/includes/inc_catalog.html' %}
    <div class="container">
        <div class="row text-start">
            <div class="col-md-6">
                <div class="card mb-4 box-shadow" Style="border-color:#7777ff">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/one_product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    {% include 'catalog/includes/inc_product.html' %}
    <div class="container">
        <div class="row text-center">
            <div class="col-12">
                <div class="card mb-4 box-shadow" Style="border-color:#7777ff">
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">Цена в розницу: {{ object_list.price }} руб. </h1>
                        <div class="card shadow-sm">
                            <p><img src="{% mediapath object_list.image %}" width="200"></p>
                        </div>
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Описание:</td>
                                <td>{{ object_list.description_product|truncatechars:500 }}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Категория:</td>
                                <td>{{ object_list.name_category }}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Дата последнего изменения:</td>
                                <td>{{ object_list.updated_at }}</td>
                            </tr>
                        </table>
                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">В корзину</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    {#    {% include 'catalog/includes/inc_product.html' %}#}
    {% include 'catalog/includes/inc_catalog.html' %}
    <div class="container">
        <div class="row text-center" style="display: flex;flex-wrap: wrap;align-items: stretch;">
            <div class="col-12 mb-3">
                <a href="{% url 'catalog:product_create' %}">Добавить</a>
            </div>
                <div class="container">
                    <div class="col-12 text-center mb-3">
                        {% if page_obj.has_other_pages %}
                            {% if page_obj.has_previous %}
                                <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">Назад</a>
                            {% endif %}
                            {% if page_obj.has_next %}
                                &nbsp;&nbsp;|&nbsp;&nbsp;
                                <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">Далее</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            {% for object in object_list %}
                <div class="col-4">
                    <div class="card-group mb-4">
                        <div class="card" style="display: flex; border-color:#7777ff;  flex-direction:column;
                        justify-content: space-between;   height: auto;">
                            <p><img src="{% mediapath object.image %}" alt="продукты" class="img-fluid"
                                    style="width:150px; height: 150px;"></p>
                            <div class="card-body">
                                <h6 class="card-title">{{ object.name_product|truncatechars:25 }}</h6>
                                <h4 class="card-title pricing-card-title">{{ object.price }} ₽</h4>
                            </div>
                            <a href="/one_product/{{ object.pk }}" type="button"
                               class="card-link">Детальная информация</a>
                            <br>
                            <h6 class="my-0 font-weight-normal mb-3">{{ object.name }}
                                {% if object.active_version_number %}
                                    <p>Активная версия: {{ object.active_version_number }}</p>
                                    <p>Статус: {{ object.active_version_name }}</p>
                                {% endif %}
                            </h6>
{#                        {% if perms.catalog.change_product %}#}
                        <div class="card-footer">
                                <a class="btn btn-link"
                                   href="{% url 'catalog:product_update' object.pk %}">Редактировать</a>
                                <a class="btn btn-link" href="{% url 'catalog:product_delete' object.pk %}">Удалить</a>
                                <small class="text-muted"></small>
                            </div>
{#                        {% endif %}#}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}